### PR TITLE
Updated the CRA to 3.4.1

### PR DESCRIPTION
**Pull request by Jagatmachines**
v3.4.1 is a maintenance release that includes minor bug fixes and documentation updates including upgrading Babel to fix a bug in the 7.8 release line. This release also brings support for TypeScript 3.8.

bug Bug Fix
react-scripts
#8276 Use native ESLint behaviour when extending (@mrmckeb)
#7203 Closes webpack dev server and exits process on "end" stdin (@kelseyleftwich)
babel-preset-react-app
#8526 Fix optional chaining and nullish coalescing support (@ianschmitz)
cra-template, eslint-config-react-app, react-scripts
#7790 Widen eslint-config-react-app peer dependency versions (@lukyth)
nail_care Enhancement
cra-template-typescript, cra-template
#8558 Add React.StrictMode to default templates (@connkat)
react-scripts
#8539 allow specification of package.main in template.json (@EvanBoyle)
memo Documentation
Other
#8515 Fix proxying API request docs (@hjr3)
#8561 Indicate that the file structure is the template's (@Vinnl)
react-scripts
#8276 Use native ESLint behaviour when extending (@mrmckeb)
hammer Underlying Tools
babel-preset-react-app, create-react-app, react-dev-utils, react-error-overlay, react-scripts
#8681 Update to Babel 7.9 (@ianschmitz)
#8620 Bump dependencies (@ianschmitz)
react-scripts
#8509 Bumps pnp-webpack-plugin (@arcanis)
Committers: 9
Brody McKee (@mrmckeb)
Evan Boyle (@EvanBoyle)
Herman J. Radtke III (@hjr3)
Ian Schmitz (@ianschmitz)
Kanitkorn Sujautra (@lukyth)
KatCon (@connkat)
Kelsey Leftwich (@kelseyleftwich)
Maël Nison (@arcanis)
Vincent (@Vinnl)

### CODE REVIEW

**Comment by Jagatmachines** [comment]
@F1LT3R please review the PR in order to update


bug Bug Fix
react-scripts
#8276 Use native ESLint behaviour when extending (@mrmckeb)
#7203 Closes webpack dev server and exits process on "end" stdin (@kelseyleftwich)
babel-preset-react-app
#8526 Fix optional chaining and nullish coalescing support (@ianschmitz)
cra-template, eslint-config-react-app, react-scripts
#7790 Widen eslint-config-react-app peer dependency versions (@lukyth)
nail_care Enhancement
cra-template-typescript, cra-template
#8558 Add React.StrictMode to default templates (@connkat)
react-scripts
#8539 allow specification of package.main in template.json (@EvanBoyle)
memo Documentation
Other
#8515 Fix proxying API request docs (@hjr3)
#8561 Indicate that the file structure is the template's (@Vinnl)
react-scripts
#8276 Use native ESLint behaviour when extending (@mrmckeb)
hammer Underlying Tools
babel-preset-react-app, create-react-app, react-dev-utils, react-error-overlay, react-scripts
#8681 Update to Babel 7.9 (@ianschmitz)
#8620 Bump dependencies (@ianschmitz)
react-scripts
#8509 Bumps pnp-webpack-plugin (@arcanis)

**Comment by jmyrland** [comment]
@F1LT3R any chance of getting this change merged?

**Comment by Zemnmez** [comment]
I'm guessing this fixes https://github.com/react-workspaces/create-react-app/issues/27. Would be great to see this merged.

**Comment by F1LT3R** [comment]
I will try to publish and merge tomorrow. You are welcome to contact me in the chat room if you want me to look at these requests faster.

Also, if someone else wants to take on the responsibility of doing this going forward, let me know.

**Comment by Zemnmez** [comment]
Thanks so much @F1LT3R! I've been using my fork of @Jagatmachines's revision and it's been going great. Had trouble getting into the chat room. Would be happy to take a look at some of these but I'd probably stop at actually merging without a reviewer since I don't have a lot of historical context on this repo.

**Comment by Jagatmachines** [comment]
@F1LT3R provide us the slack link, i m not able to find it in the repo as there is only picture but no link while clicking it

**Comment by Jagatmachines** [comment]
I will be closing this pull request and requesting for a new one with 3.4.1 update #28 
@F1LT3R @jmyrland please take a look whenever you are free
not able to tag Zemnmez for some reason

>

**Pull request closed without merging**
