### PR TITLE
Updating react-workspace/react-script version 3.3.0 to facebook/react-script 3.4.0

### PR DESCRIPTION
**Pull request by Jagatmachines**
Updating react-workspace/react-script version 3.3.0 to facebook/react-script 3.4.0 for Downgrade style-loader to v0.23.1 due to CSS modules hot reload not working with v1.0.0

### CODE REVIEW

**Comment by leovanhaaren** [comment]
Can we please have this merged @F1LT3R

**Comment by jukkahuuskonen** [comment]
Any timetable for this merge? This causes quite a few problems.

**Comment by alanrubin** [comment]
3.3.0 has a couple of issues so it would be really good to upgrade to 3.4.0, any ideas when that will be done? Thank you very much!

**Comment by F1LT3R** [comment]
@alanrubin @jukkahuuskonen @leovanhaaren @Jagatmachines ...
Merged.
Do you need me to publish to npm?

**Comment by alanrubin** [comment]
Yes please, thank you!

**Comment by alanrubin** [comment]
Hey, did you manage to publish it? In npm, it still shows 3.3.0-alpha-08, thanks!

**Comment by leovanhaaren** [comment]
@F1LT3R can this be published to NPM please? Thanks!

**Comment by jakubhomoly** [comment]
@F1LT3R Could you please publish the new version? Thank you!

**Comment by F1LT3R** [comment]
Published version `@react-workspaces/react-scripts` version `3.4.0-alpha-01`.

FYI: Feel free to join me on Slack if you need a faster response. 

https://join.slack.com/t/react-workspaces/shared_invite/zt-dx88pvp1-qUphnsiM7CmF2ll0wo_sPA

**Pull request merged**
